### ISSUE TITLE
HOTFIX: baseUrl from .env

### ISSUE THREAD

**Issue by 63phc** [littleknitsstory/frontend#31]
https://github.com/littleknitsstory/frontend/blob/develop/src/api/apiClient.ts#L41

```
pahan@debian:/home/lks/front_dev$ cat .env
REACT_APP_API_BASE = http://dev.backend.littleknitsstory.com:26363/api/v1
```

**Comment by Blackk88** [comment]
Мы сейчас переделываем fetch запросы через RTK Query. В понедельник зальем, там уже будет новый baseURL
