### ISSUE TITLE
Поле телефон в личном кабинете принимает буквы и не принимает спец символы + ()

### ISSUE THREAD

**Issue by Freeman22222** [littleknitsstory/frontend#79]
Поле ввода номера в личном кабинете не принимает номер формата +7(931)1234567 при этом тост об ошибке или обновлении номера не появляется, информация просто не записывается.
При этом обновленная информация в других полях так же не обновляется.
Можно писать буквы и другие спец символы в поле с телефоном, заполнить все поля, уйти со страницы профиля, вернуться на нее и не найти ранее введенные данные.

проверял здесь
http://dev.littleknitsstory.com/profile

1 заходим в созданный ранее профиль пользователя
2 в поле телефон вводим +7(931)1234567

Ожидаемый результат: телефон сохранен в профиле
Фактический результат: Поле не принимает введенные данные, сообщениe об ошибке не выводится

![Image](https://user-images.githubusercontent.com/107580845/230093909-c43eba33-690f-4b8d-86e9-37fed85be69d.png)

![Image](https://user-images.githubusercontent.com/107580845/230096887-3cd4f3a8-297c-474f-bd7a-7ceca6ea2d8a.png)

**Comment by Blackk88** [comment]
Валидацию на фронте пока не добавлял. Нет ощущения, что это конечные поля, которые будут на этой странице и сейчас меняют апишку для профиля.
Кроме того на беке, для конкретного этого поля 
<img width="549" alt="Screenshot 2023-04-05 at 22 31 15" src="https://user-images.githubusercontent.com/108989350/230204800-227f4fba-9950-46df-a90a-97399020b885.png">
стоит ограничение 13 символов - поэтому вариант со скобками не проходит.

**Comment by Freeman22222** [comment]
я могу ввести в это поле больше 13 знаков
нужно запретить ввод после 14 знака тогда
